emo_fake_true_12={
        "Fake-Angry":0,
        "Fake-Contempt":1,
        "Fake-Disgust":2,
        "Fake-Happy":3,
        "Fake-Sad":4,
        "Fake-Surprise":5,
        "Real-Angry":6,
        "Real-Contempt":7,
        "Real-Disgust":8,
        "Real-Happy":9,
        "Real-Sad":10,
        "Real-Surprise":11
        
}

emofake_true={
        "Fake-Angry":0,
        "Fake-Contempt":0,
        "Fake-Disgust":0,
        "Fake-Happy":0,
        "Fake-Sad":0,
        "Fake-Surprise":0,
        "Real-Angry":1,
        "Real-Contempt":1,
        "Real-Disgust":1,
        "Real-Happy":1,
        "Real-Sad":1,
        "Real-Surprise":1
        
}
emo_basic_6={
        "Fake-Angry":0,
        "Fake-Contempt":1,
        "Fake-Disgust":2,
        "Fake-Happy":3,
        "Fake-Sad":4,
        "Fake-Surprise":5,
        "Real-Angry":0,
        "Real-Contempt":1,
        "Real-Disgust":2,
        "Real-Happy":3,
        "Real-Sad":4,
        "Real-Surprise":5
}

int2emo={
        0:"Fake-Angry",
        1:"Fake-Contempt",
        2:"Fake-Disgust",
        3:"Fake-Happy",
        4:"Fake-Sad",
        5:"Fake-Surprise",
        6:"Real-Angry",
        7:"Real-Contempt",
        8:"Real-Disgust",
        9:"Real-Happy",
        10:"Real-Sad",
        11:"Real-Surprise"
        
}